Changed review stars to blade
rapidez/reviews pull request #29
Opened 2024-12-20 07:56 UTC by JimmyHoenderdaal

2024-12-20 08:03 UTC, Roene-JustBetter approved these changes

2024-12-20 08:35 UTC, Roene-JustBetter submitted a review, later dismissed

2024-12-20 14:14 UTC, indykoning submitted a review, later dismissed

2024-12-20 14:28 UTC, royduin commented on resources/views/components/stars.blade.php
> +        >
Could this be written cleaner with `@attributes()`? See: https://github.com/rapidez/blade-directives#attributes or is this the cleanest option?

2024-12-24 10:32 UTC, jordythevulder approved these changes

2025-01-13 11:50 UTC, JimmyHoenderdaal commented on resources/views/components/stars.blade.php
> +        >
I think it is the cleanest option, since otherwise you would have something like this
```
@attributes(['v-bind:style' => $attributes->has('v-bind:score') ? "{ width: (" . $attributes['v-bind:score'] . " || 0) + '%'}" : null])
```

which in my opinion makes it a bit abstract and less readable

2025-01-14 10:10 UTC, royduin commented on resources/views/components/stars.blade.php
> +        >
What about just:

```suggestion
        <div
            v-bind:style="{ width: ({{ $score }} || 0) + '%'}"
            class="absolute inset-0 flex gap-0.5 overflow-hidden"
        >
```

With that this can be used as:

1. `score="{{ $product->reviews_score }}"`
2. `score="item.reviews_score"`

The only "drawback" of this is that the "php version" (number 1) will render with Vue instead of directly. But when there aren't any shifts that's not a big problem. But you could also fix that with something like:

```suggestion
        <div
            @if(is_int($score))
                style="width: {{ $score }}%"
            @endif
            v-bind:style="{ width: ({{ $score }} || 0) + '%'}"
            class="absolute inset-0 flex gap-0.5 overflow-hidden"
        >
```

or to keep it inline:

```suggestion
        <div
            style="width: {{ is_int($score) ? $score : 0 }}%"
            v-bind:style="{ width: ({{ $score }} || 0) + '%'}"
            class="absolute inset-0 flex gap-0.5 overflow-hidden"
        >
```

But as casting a string to an integer results in 0;

```suggestion
        <div
            style="width: {{ (int)$score }}%"
            v-bind:style="{ width: ({{ $score }} || 0) + '%'}"
            class="absolute inset-0 flex gap-0.5 overflow-hidden"
        >
```

Having 1 "source" is maybe a cleaner approach.

2025-01-15 13:20 UTC, royduin requested changes
Did you test everything?

2025-01-15 13:20 UTC, royduin commented on resources/views/components/stars.blade.php
> +    @endif
Can we apply a similar idea as with the score here? So it's working in both cases; Blade and Vue?

2025-01-15 14:45 UTC, royduin commented on README.md
> +<x-rapidez-reviews::stars v-if="item.reviews_count" v-bind:count="item.reviews_count" v-bind:score="item.reviews_score"/>
This example is outdated?

2025-01-15 14:45 UTC, royduin commented on resources/views/form.blade.php
> +                                <div v-if="data" v-cloak slot-scope="{ data }">
I prefer to have the `v-cloak` at the end.

2025-01-15 15:08 UTC, merged